version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app:Z  # SELinux requires volume mount workaround
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1  # set to 0 in production
    